my-backend:
  image:
    repository: stefanprodan/podinfo
    tag: latest
  containerPort: 9898
  service:
    port: 9898
  ingress:
    enabled: true
    host: api-hello.127.0.0.1.nip.io
  serviceMonitor:
    enabled: true
    namespace: metrics
    path: /metrics
    interval: 30s
    labels:
      release: lens-metrics
